language: node_js

node_js:
  - "11"

cache: npm

script: npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master

notifications:
  email: false
